name: climai_global
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - numpy=1.23.5
  - pytorch-cuda=11.7
  - pip=21.2.4 # See https://github.com/Azure/MachineLearningNotebooks/issues/1110 - using this specific pip works around ruamel.yaml not found error.
  - pytest=7.1.2
  - python=3.9.13
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-lightning[strategies]=1.9.4
  - torchdata=0.6.1
  - hydra-core=1.3.1
  - xesmf=0.7.1
  - cfgrib=0.9.8.0 # Higher versions generate a lot of errors and warnings.
  - xarray=2023.3.0 # Latest that supports cfgrib 0.9.8.5
  - netCDF4=1.6.3 # necessary to open .nc files
  - pip:
    - aiofiles==23.1.0
    - timm==0.6.13
    - omegaconf==2.3.0
    - jsonargparse[signatures]==4.19.0
    - lightning-bolts==0.5.0
    - lightning-utilities==0.8.0
    - tqdm==4.64
    - cdsapi==0.6.1
    - tensorboard==2.12.2
    - multiurl==0.2.1
    - rich==13.3.1
    - deepspeed==0.7.0
    - azure-storage-blob==12.16.0
    - azure-common==1.1.28
    - azure-identity==1.13.0
    - azure-mgmt==4.0.0
    - msrestazure==0.6.4
    - joblib==1.2.0
    - geopy==2.3.0
    - einops==0.6.1